#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
venv_dir="${repo_root}/.venv-vision"
vision_site_packages=""

if [[ ! -x "${venv_dir}/bin/python" ]]; then
  echo "Vision environment not found. Run tools/setup_ubuntu_vision.sh first." >&2
  exit 1
fi
if [[ ! -f "${repo_root}/install/setup.bash" ]]; then
  echo "ROS workspace is not built. Run tools/setup_ubuntu_vision.sh first." >&2
  exit 1
fi

vision_site_packages="$(
  "${venv_dir}/bin/python" -c \
    'import sysconfig; print(sysconfig.get_path("purelib"))'
)"
if [[ ! -d "${vision_site_packages}" ]]; then
  echo "Vision site-packages not found: ${vision_site_packages}" >&2
  exit 1
fi

# ROS console scripts may have been regenerated by a normal system-Python
# colcon build. Keep the vision venv dependencies visible even when an
# installed entry point has /usr/bin/python3 in its shebang.
export PYTHONPATH="${vision_site_packages}${PYTHONPATH:+:${PYTHONPATH}}"

set +u
source /opt/ros/jazzy/setup.bash
source "${venv_dir}/bin/activate"
source "${repo_root}/install/setup.bash"
set -u

exec ros2 launch rebotarm_vision vision_ubuntu.launch.py "$@"
